# frozen_string_literal: true

require "psych"

module AspaceDataTools
  module Doc
    module_function

    # @return [Hash] keys are schema names, values are the schemas
    def schemas = @schemas ||= ADT.client
      .get("/schemas")
      .parsed
      .sort_by { |k, v| k }
      .to_h

    # @return [Hash] endpoints are schemas with a uri property
    def endpoints = @endpoints ||= schemas.select { |k, v| v.key?("uri") }
      .to_h

    # @param name [String] jsonmodel_type of record
    # @return [ADT::Doc::Rectype]
    def get_rectype(name)
      fetched = rectypes.find { |rt| rt.name == name }
      return fetched if fetched

      result = ADT.client.get("/schemas/#{name}")
      if result.status_code == 200
        return Rectype.new(name, result.parsed)
      end

      fail("#{result.status}\n#{result.parsed}")
    end

    # @return [Array<ADT::Doc::Rectype>] primary record types
    def rectypes
      @rectypes ||= Rectypes.new.call
    end

    # @return [Array<ADT::Doc::Property]
    def properties = rectypes.map(&:properties)
      .flatten

    # @param norm [Hash] normalized property config
    # @return [Array<ADT::Doc::Property]
    def properties_by_norm(norm)
      properties.select { |p| p.normalize_config == norm }
        .sort_by { |p| "#{p.rectype} #{p.name}" }
    end

    def reqfields
      rectypes.each do |rt|
        puts "#{rt.name}:\n#{rt.required_fields.join(",")}\n\n"
      end
      nil
    end

    # @return [Hash] parsed locale file value for "en"
    def locales = @locales ||= get_locales

    # @return [Hash] with machine names as keys, display names as values
    #   The `_singular` label for a record type/jsonmodel in locales is
    #   used for the display name. Some rectypes/jsonmodels do not have entries
    #   in locales. The display names for these are generated by replacing
    #   underscores in the machine name with spaces and capitalizing each word.
    def rectype_displayname_lookup
      ADT.rectypes
        .map { |rt| [rt.name, locales.dig(rt.name, "_singular")] }
        .to_h
        .map do |k, v|
          next [k, v] if v

          [k, k.split("_").map(&:capitalize).join(" ")]
        end.to_h
    end

    def get_locales
      Psych.load_file(ADT.config.locales_path, aliases: true)["en"]
    end
    private_class_method(:get_locales)
  end
end
