# frozen_string_literal: true

require "psych"

module AspaceDataTools
  module Doc
    module_function

    def locales = @locales ||= get_locales

    # @return [Hash] with machine names as keys, display names as values
    #   The `_singular` label for a record type/jsonmodel in locales is
    #   used for the display name. Some rectypes/jsonmodels do not have entries
    #   in locales. The display names for these are generated by replacing
    #   underscores in the machine name with spaces and capitalizing each word.
    def rectype_displayname_lookup
      ADT.rectypes
        .map { |rt| [rt.name, locales.dig(rt.name, "_singular")] }
        .to_h
        .map do |k, v|
          next [k, v] if v

          [k, k.split("_").map(&:capitalize).join(" ")]
        end.to_h
    end

    def get_locales
      result = ADT::Doc::UpdateLocales.new.call
      return {} if result == :failure

      Psych.load_file(ADT.locales_file, aliases: true)["en"]
    end
    private_class_method(:get_locales)
  end
end
